import {
  IconBook,
  IconBookUpload,
  IconBrain,
  IconChartBar,
  IconDashboard,
  IconHeadphones,
  IconHeadset,
  IconHome,
  IconListCheck,
  IconMessageChatbot,
  IconMicrophone,
  IconNotebook,
  IconPencilCheck,
  IconUsersGroup,
} from '@tabler/icons-react'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
  {
    key: 'dashboard',
    path: '/dashboard',
    title: 'Trang chủ',
    translateKey: 'nav.home',
    icon: IconHome,
    authority: [],
    subMenu: [],
  },
  {
    key: 'vocabulary',
    path: '/vocabulary',
    title: 'Từ vựng',
    translateKey: 'nav.vocabulary',
    icon: IconBook,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'grammar',
    path: '/grammar',
    title: 'Ngữ pháp',
    translateKey: 'nav.grammar',
    icon: IconBrain,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'listening',
    path: '/listening',
    title: 'Nghe',
    translateKey: 'nav.listening',
    icon: IconHeadphones,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'speaking',
    path: '/speaking',
    title: 'Nói',
    translateKey: 'nav.speaking',
    icon: IconMicrophone,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'ielts-practice',
    path: '/ielts-practice',
    title: 'Luyện đề IELTS',
    translateKey: 'nav.ieltsPractice',
    icon: IconListCheck,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'writing-check',
    path: '/writing-check',
    title: 'AI Chấm bài viết',
    translateKey: 'nav.writingCheck',
    icon: IconPencilCheck,
    authority: ['STUDENT'],
    subMenu: [],
  },
  {
    key: 'ai-chat',
    path: '/ai-chat',
    title: 'AI Chatbot',
    translateKey: 'nav.aiChat',
    icon: IconMessageChatbot,
    authority: ['STUDENT'],
    subMenu: [],
  },
  // ── Teacher Management ─────────────────────────────────────────────────────
  {
    key: 'teacher.divider',
    path: '',
    title: 'Quản lý nội dung',
    translateKey: 'nav.teacherDivider',
    icon: null,
    type: 'title',
    authority: ['TEACHER'],
    subMenu: [],
  },
  {
    key: 'teacher.vocabulary',
    path: '/teacher/vocabulary',
    title: 'QL Từ vựng',
    translateKey: 'nav.teacherVocabulary',
    icon: IconBookUpload,
    authority: ['TEACHER'],
    subMenu: [],
  },
  {
    key: 'teacher.grammar',
    path: '/teacher/grammar',
    title: 'QL Ngữ pháp',
    translateKey: 'nav.teacherGrammar',
    icon: IconNotebook,
    authority: ['TEACHER'],
    subMenu: [],
  },
  {
    key: 'teacher.listening',
    path: '/teacher/listening',
    title: 'QL Luyện nghe',
    translateKey: 'nav.teacherListening',
    icon: IconHeadset,
    authority: ['TEACHER'],
    subMenu: [],
  },
  // ── Admin ──────────────────────────────────────────────────────────────────
  {
    key: 'admin.divider',
    path: '',
    title: 'Quản trị hệ thống',
    translateKey: 'nav.adminDivider',
    icon: null,
    type: 'title',
    authority: ['ADMIN'],
    subMenu: [],
  },
  {
    key: 'admin.dashboard',
    path: '/admin',
    title: 'Bảng điều khiển',
    translateKey: 'nav.adminDashboard',
    icon: IconDashboard,
    authority: ['ADMIN'],
    subMenu: [],
  },
  {
    key: 'admin.users',
    path: '/admin/users',
    title: 'Quản lý người dùng',
    translateKey: 'nav.adminUsers',
    icon: IconUsersGroup,
    authority: ['ADMIN'],
    subMenu: [],
  },
  {
    key: 'admin.content',
    path: '/admin/content',
    title: 'Quản lý nội dung',
    translateKey: 'nav.adminContent',
    icon: IconChartBar,
    authority: ['ADMIN'],
    subMenu: [],
  },
]

export default navigationConfig
